module.exports = [{"_id":"639dc1fa2d088983c679611a",
"name":"Perso test",
"age":"358",
"oeilD":"bleu",
"oeilG":"vert",
"taille":"190",
"poids":"85",
"sexe":"N.D.",
"planete":"manta",
"agence":"Estrella",
"cheveux":"blonds",
"race":"vemp'yr",
"metier":"guerrier",
"niveau":1,
"signesDistinctifs":"bernbmonerm vkjmeboizrg veribvre gimub zrkg friumgb rkjgmbrgbrmigb kjgmbrrg eribg erkjmg g",
"traitsDeCaractere":"ezogberomg jfezrngrle gjuierbgejkbtkr:ebgergjkgbgterjk brk biorhtn rkuhgerkgheroiv reiug h erjghejguie gnoidghnlk bhrlhdfoigfoigeroigheri gherio eoih greoi gheroi greig hrimdg",
"manaAir":"100",
"manaEau":"100",
"manaTerre":"100",
"manaFeu":"100",
"stamina":"100",
"manaVie":"400",
"force":"50",
"dexterite":"50",
"resistance":"50",
"resilience":"50",
"intelligence":"50",
"charisme":"50",
"chance":"nr",
"bien":"0",
"mal":"25",
"xalytienArchaique":"30",
"xalytienAntique":"30",
"xalytienDemonique":"30",
"xentoArchaique":"30",
"xentoAntique":"30",
"xentoDemonique":"30",
"zenolmArchaique":"30",
"zenolmAntique":"30",
"zenolmDemonique":"30",
"justiccelArchaique":"30",
"justiccelAntique":"30",
"justiccelDemonique":"30",
"zombique":"40",
"faerik":"40",
"elfik":"40",
"nanien":"30",
"gnomique":"50",
"tenebriale":"30",
"noyale":"20",
"elementale":"30",
"celeste":"45",
"mainsNues":"43",
"jets":"33",
"contondantes":"23",
"courtes":"33",
"longues":"55",
"esquive":"56",
"parade":"44",
"chant":"43",
"chasse":"33",
"course":"33",
"crochetage":"44",
"discretion":"33",
"eloquence":"33",
"equitation":"33",
"escalade":"33",
"herboristerie":"33",
"hypnose":"33",
"marchandage":"33",
"medecine":"33",
"nage":"33",
"observation":"33",
"pieges":"33",
"pistage":"33",
"professorat":"33",
"saut":"33",
"soin":"33",
"survie":"33",
"telekinesie":"33",
"vigilence":"33",
"magicoTech":"33",
"cartographie":"33",
"potions":"33",
"theorieDesMagies":"33",
"histoireMagique":"33",
"magieAir":"33",
"magieEau":"33",
"magieTerre":"33",
"magieFeu":"33",
"magieElec":"33",
"crea":"33",
"psyInt":"33",
"psyPerso":"33",
"instinct":"33",
"auraLectrice":"55",
"chaleur":"44",
"vapeur":"44",
"magieVie":"44",
"temps":"44",
"mort":"44",
"magnetisme":"44",
"oxygene":"44",
"foudre":"44",
"flying":"44",
"molecule":"44",
"metaux":"44",
"psyExt":"44",
"psyInterperso":"44",
"auraManipulatrice":"44",
"genbu":"33",
"oiseauTonnerre":"33",
"ginnungagap":"33",
"phoinix":"33",
"klabautermann":"33",
"thiyatHametim":"33",
"mortemRejiciunt":"33",
"yomHaDim":"33",
"vitaBrevis":"33",
"lostAge":"33",
"sunganIdong":"33",
"auraCombinatoire":"33",
"lumiere":"33",
"ombres":"33",
"sang":"33",
"fluides":"33",
"energie":"33",
"sons":"33",
"magieAstrale":"33",
"magieSpectrale":"33",
"cosmos":"33",
"savoir":"33",
"tenebres":"33",
"oubli":"33",
"clairObscur":"33",
"plantes":"33",
"adn":"33",
"fer":"33",
"plasma":"33",
"ondes":"33",
"magieDraconique":"33"
}
// ,
// {"_id":"639dc1fa2d088983c679611b",
// "name":"Perso test",
// "age":"358",
// "oeilD":"bleu",
// "oeilG":"vert",
// "taille":"190",
// "poids":"85",
// "sexe":"N.D.",
// "planete":"manta",
// "agence":"Estrella",
// "cheveux":"blonds",
// "race":"vemp'yr",
// "metier":"guerrier",
// "niveau":1,
// "signesDistinctifs":"bernbmonerm vkjmeboizrg veribvre gimub zrkg friumgb rkjgmbrgbrmigb kjgmbrrg eribg erkjmg g",
// "traitsDeCaractere":"ezogberomg jfezrngrle gjuierbgejkbtkr:ebgergjkgbgterjk brk biorhtn rkuhgerkgheroiv reiug h erjghejguie gnoidghnlk bhrlhdfoigfoigeroigheri gherio eoih greoi gheroi greig hrimdg",
// "manaAir":"100",
// "manaEau":"100",
// "manaTerre":"100",
// "manaFeu":"100",
// "stamina":"100",
// "manaVie":"400",
// "force":"50",
// "dexterite":"50",
// "resistance":"50",
// "resilience":"50",
// "intelligence":"50",
// "charisme":"50",
// "chance":"nr",
// "bien":"0",
// "mal":"25",
// "xalytienArchaique":"30",
// "xalytienAntique":"30",
// "xalytienDemonique":"30",
// "xentoArchaique":"30",
// "xentoAntique":"30",
// "xentoDemonique":"30",
// "zenolmArchaique":"30",
// "zenolmAntique":"30",
// "zenolmDemonique":"30",
// "justiccelArchaique":"30",
// "justiccelAntique":"30",
// "justiccelDemonique":"30",
// "zombique":"40",
// "faerik":"40",
// "elfik":"40",
// "nanien":"30",
// "gnomique":"50",
// "tenebriale":"30",
// "noyale":"20",
// "elementale":"30",
// "celeste":"45",
// "mainsNues":"43",
// "jets":"33",
// "contondantes":"23",
// "courtes":"33",
// "longues":"55",
// "esquive":"56",
// "parade":"44",
// "chant":"43",
// "chasse":"33",
// "course":"33",
// "crochetage":"44",
// "discretion":"33",
// "eloquence":"33",
// "equitation":"33",
// "escalade":"33",
// "herboristerie":"33",
// "hypnose":"33",
// "marchandage":"33",
// "medecine":"33",
// "nage":"33",
// "observation":"33",
// "pieges":"33",
// "pistage":"33",
// "professorat":"33",
// "saut":"33",
// "soin":"33",
// "survie":"33",
// "telekinesie":"33",
// "vigilence":"33",
// "magicoTech":"33",
// "cartographie":"33",
// "potions":"33",
// "theorieDesMagies":"33",
// "histoireMagique":"33",
// "magieAir":"33",
// "magieEau":"33",
// "magieTerre":"33",
// "magieFeu":"33",
// "magieElec":"33",
// "crea":"33",
// "psyInt":"33",
// "psyPerso":"33",
// "instinct":"33",
// "auraLectrice":"55",
// "chaleur":"44",
// "vapeur":"44",
// "magieVie":"44",
// "temps":"44",
// "mort":"44",
// "magnetisme":"44",
// "oxygene":"44",
// "foudre":"44",
// "flying":"44",
// "molecule":"44",
// "metaux":"44",
// "psyExt":"44",
// "psyInterperso":"44",
// "auraManipulatrice":"44",
// "genbu":"33",
// "oiseauTonnerre":"33",
// "ginnungagap":"33",
// "phoinix":"33",
// "klabautermann":"33",
// "thiyatHametim":"33",
// "mortemRejiciunt":"33",
// "yomHaDim":"33",
// "vitaBrevis":"33",
// "lostAge":"33",
// "sunganIdong":"33",
// "auraCombinatoire":"33",
// "lumiere":"33",
// "ombres":"33",
// "sang":"33",
// "fluides":"33",
// "energie":"33",
// "sons":"33",
// "magieAstrale":"33",
// "magieSpectrale":"33",
// "cosmos":"33",
// "savoir":"33",
// "tenebres":"33",
// "oubli":"33",
// "clairObscur":"33",
// "plantes":"33",
// "adn":"33",
// "fer":"33",
// "plasma":"33",
// "ondes":"33",
// "magieDraconique":"33"
// },
// {"_id":"639dc1fa2d088983c679611c",
// "name":"Perso test",
// "age":"358",
// "oeilD":"bleu",
// "oeilG":"vert",
// "taille":"190",
// "poids":"85",
// "sexe":"N.D.",
// "planete":"manta",
// "agence":"Estrella",
// "cheveux":"blonds",
// "race":"vemp'yr",
// "metier":"guerrier",
// "niveau":1,
// "signesDistinctifs":"bernbmonerm vkjmeboizrg veribvre gimub zrkg friumgb rkjgmbrgbrmigb kjgmbrrg eribg erkjmg g",
// "traitsDeCaractere":"ezogberomg jfezrngrle gjuierbgejkbtkr:ebgergjkgbgterjk brk biorhtn rkuhgerkgheroiv reiug h erjghejguie gnoidghnlk bhrlhdfoigfoigeroigheri gherio eoih greoi gheroi greig hrimdg",
// "manaAir":"100",
// "manaEau":"100",
// "manaTerre":"100",
// "manaFeu":"100",
// "stamina":"100",
// "manaVie":"400",
// "force":"50",
// "dexterite":"50",
// "resistance":"50",
// "resilience":"50",
// "intelligence":"50",
// "charisme":"50",
// "chance":"nr",
// "bien":"0",
// "mal":"25",
// "xalytienArchaique":"30",
// "xalytienAntique":"30",
// "xalytienDemonique":"30",
// "xentoArchaique":"30",
// "xentoAntique":"30",
// "xentoDemonique":"30",
// "zenolmArchaique":"30",
// "zenolmAntique":"30",
// "zenolmDemonique":"30",
// "justiccelArchaique":"30",
// "justiccelAntique":"30",
// "justiccelDemonique":"30",
// "zombique":"40",
// "faerik":"40",
// "elfik":"40",
// "nanien":"30",
// "gnomique":"50",
// "tenebriale":"30",
// "noyale":"20",
// "elementale":"30",
// "celeste":"45",
// "mainsNues":"43",
// "jets":"33",
// "contondantes":"23",
// "courtes":"33",
// "longues":"55",
// "esquive":"56",
// "parade":"44",
// "chant":"43",
// "chasse":"33",
// "course":"33",
// "crochetage":"44",
// "discretion":"33",
// "eloquence":"33",
// "equitation":"33",
// "escalade":"33",
// "herboristerie":"33",
// "hypnose":"33",
// "marchandage":"33",
// "medecine":"33",
// "nage":"33",
// "observation":"33",
// "pieges":"33",
// "pistage":"33",
// "professorat":"33",
// "saut":"33",
// "soin":"33",
// "survie":"33",
// "telekinesie":"33",
// "vigilence":"33",
// "magicoTech":"33",
// "cartographie":"33",
// "potions":"33",
// "theorieDesMagies":"33",
// "histoireMagique":"33",
// "magieAir":"33",
// "magieEau":"33",
// "magieTerre":"33",
// "magieFeu":"33",
// "magieElec":"33",
// "crea":"33",
// "psyInt":"33",
// "psyPerso":"33",
// "instinct":"33",
// "auraLectrice":"55",
// "chaleur":"44",
// "vapeur":"44",
// "magieVie":"44",
// "temps":"44",
// "mort":"44",
// "magnetisme":"44",
// "oxygene":"44",
// "foudre":"44",
// "flying":"44",
// "molecule":"44",
// "metaux":"44",
// "psyExt":"44",
// "psyInterperso":"44",
// "auraManipulatrice":"44",
// "genbu":"33",
// "oiseauTonnerre":"33",
// "ginnungagap":"33",
// "phoinix":"33",
// "klabautermann":"33",
// "thiyatHametim":"33",
// "mortemRejiciunt":"33",
// "yomHaDim":"33",
// "vitaBrevis":"33",
// "lostAge":"33",
// "sunganIdong":"33",
// "auraCombinatoire":"33",
// "lumiere":"33",
// "ombres":"33",
// "sang":"33",
// "fluides":"33",
// "energie":"33",
// "sons":"33",
// "magieAstrale":"33",
// "magieSpectrale":"33",
// "cosmos":"33",
// "savoir":"33",
// "tenebres":"33",
// "oubli":"33",
// "clairObscur":"33",
// "plantes":"33",
// "adn":"33",
// "fer":"33",
// "plasma":"33",
// "ondes":"33",
// "magieDraconique":"33"
// },
// {"_id":"639dc1fa2d088983c679611d",
// "name":"Perso test",
// "age":"358",
// "oeilD":"bleu",
// "oeilG":"vert",
// "taille":"190",
// "poids":"85",
// "sexe":"N.D.",
// "planete":"manta",
// "agence":"Estrella",
// "cheveux":"blonds",
// "race":"vemp'yr",
// "metier":"guerrier",
// "niveau":1,
// "signesDistinctifs":"bernbmonerm vkjmeboizrg veribvre gimub zrkg friumgb rkjgmbrgbrmigb kjgmbrrg eribg erkjmg g",
// "traitsDeCaractere":"ezogberomg jfezrngrle gjuierbgejkbtkr:ebgergjkgbgterjk brk biorhtn rkuhgerkgheroiv reiug h erjghejguie gnoidghnlk bhrlhdfoigfoigeroigheri gherio eoih greoi gheroi greig hrimdg",
// "manaAir":"100",
// "manaEau":"100",
// "manaTerre":"100",
// "manaFeu":"100",
// "stamina":"100",
// "manaVie":"400",
// "force":"50",
// "dexterite":"50",
// "resistance":"50",
// "resilience":"50",
// "intelligence":"50",
// "charisme":"50",
// "chance":"nr",
// "bien":"0",
// "mal":"25",
// "xalytienArchaique":"30",
// "xalytienAntique":"30",
// "xalytienDemonique":"30",
// "xentoArchaique":"30",
// "xentoAntique":"30",
// "xentoDemonique":"30",
// "zenolmArchaique":"30",
// "zenolmAntique":"30",
// "zenolmDemonique":"30",
// "justiccelArchaique":"30",
// "justiccelAntique":"30",
// "justiccelDemonique":"30",
// "zombique":"40",
// "faerik":"40",
// "elfik":"40",
// "nanien":"30",
// "gnomique":"50",
// "tenebriale":"30",
// "noyale":"20",
// "elementale":"30",
// "celeste":"45",
// "mainsNues":"43",
// "jets":"33",
// "contondantes":"23",
// "courtes":"33",
// "longues":"55",
// "esquive":"56",
// "parade":"44",
// "chant":"43",
// "chasse":"33",
// "course":"33",
// "crochetage":"44",
// "discretion":"33",
// "eloquence":"33",
// "equitation":"33",
// "escalade":"33",
// "herboristerie":"33",
// "hypnose":"33",
// "marchandage":"33",
// "medecine":"33",
// "nage":"33",
// "observation":"33",
// "pieges":"33",
// "pistage":"33",
// "professorat":"33",
// "saut":"33",
// "soin":"33",
// "survie":"33",
// "telekinesie":"33",
// "vigilence":"33",
// "magicoTech":"33",
// "cartographie":"33",
// "potions":"33",
// "theorieDesMagies":"33",
// "histoireMagique":"33",
// "magieAir":"33",
// "magieEau":"33",
// "magieTerre":"33",
// "magieFeu":"33",
// "magieElec":"33",
// "crea":"33",
// "psyInt":"33",
// "psyPerso":"33",
// "instinct":"33",
// "auraLectrice":"55",
// "chaleur":"44",
// "vapeur":"44",
// "magieVie":"44",
// "temps":"44",
// "mort":"44",
// "magnetisme":"44",
// "oxygene":"44",
// "foudre":"44",
// "flying":"44",
// "molecule":"44",
// "metaux":"44",
// "psyExt":"44",
// "psyInterperso":"44",
// "auraManipulatrice":"44",
// "genbu":"33",
// "oiseauTonnerre":"33",
// "ginnungagap":"33",
// "phoinix":"33",
// "klabautermann":"33",
// "thiyatHametim":"33",
// "mortemRejiciunt":"33",
// "yomHaDim":"33",
// "vitaBrevis":"33",
// "lostAge":"33",
// "sunganIdong":"33",
// "auraCombinatoire":"33",
// "lumiere":"33",
// "ombres":"33",
// "sang":"33",
// "fluides":"33",
// "energie":"33",
// "sons":"33",
// "magieAstrale":"33",
// "magieSpectrale":"33",
// "cosmos":"33",
// "savoir":"33",
// "tenebres":"33",
// "oubli":"33",
// "clairObscur":"33",
// "plantes":"33",
// "adn":"33",
// "fer":"33",
// "plasma":"33",
// "ondes":"33",
// "magieDraconique":"33"
// },
// {"_id":"639dc1fa2d088983c679611e",
// "name":"Perso test",
// "age":"358",
// "oeilD":"bleu",
// "oeilG":"vert",
// "taille":"190",
// "poids":"85",
// "sexe":"N.D.",
// "planete":"manta",
// "agence":"Estrella",
// "cheveux":"blonds",
// "race":"vemp'yr",
// "metier":"guerrier",
// "niveau":1,
// "signesDistinctifs":"bernbmonerm vkjmeboizrg veribvre gimub zrkg friumgb rkjgmbrgbrmigb kjgmbrrg eribg erkjmg g",
// "traitsDeCaractere":"ezogberomg jfezrngrle gjuierbgejkbtkr:ebgergjkgbgterjk brk biorhtn rkuhgerkgheroiv reiug h erjghejguie gnoidghnlk bhrlhdfoigfoigeroigheri gherio eoih greoi gheroi greig hrimdg",
// "manaAir":"100",
// "manaEau":"100",
// "manaTerre":"100",
// "manaFeu":"100",
// "stamina":"100",
// "manaVie":"400",
// "force":"50",
// "dexterite":"50",
// "resistance":"50",
// "resilience":"50",
// "intelligence":"50",
// "charisme":"50",
// "chance":"nr",
// "bien":"0",
// "mal":"25",
// "xalytienArchaique":"30",
// "xalytienAntique":"30",
// "xalytienDemonique":"30",
// "xentoArchaique":"30",
// "xentoAntique":"30",
// "xentoDemonique":"30",
// "zenolmArchaique":"30",
// "zenolmAntique":"30",
// "zenolmDemonique":"30",
// "justiccelArchaique":"30",
// "justiccelAntique":"30",
// "justiccelDemonique":"30",
// "zombique":"40",
// "faerik":"40",
// "elfik":"40",
// "nanien":"30",
// "gnomique":"50",
// "tenebriale":"30",
// "noyale":"20",
// "elementale":"30",
// "celeste":"45",
// "mainsNues":"43",
// "jets":"33",
// "contondantes":"23",
// "courtes":"33",
// "longues":"55",
// "esquive":"56",
// "parade":"44",
// "chant":"43",
// "chasse":"33",
// "course":"33",
// "crochetage":"44",
// "discretion":"33",
// "eloquence":"33",
// "equitation":"33",
// "escalade":"33",
// "herboristerie":"33",
// "hypnose":"33",
// "marchandage":"33",
// "medecine":"33",
// "nage":"33",
// "observation":"33",
// "pieges":"33",
// "pistage":"33",
// "professorat":"33",
// "saut":"33",
// "soin":"33",
// "survie":"33",
// "telekinesie":"33",
// "vigilence":"33",
// "magicoTech":"33",
// "cartographie":"33",
// "potions":"33",
// "theorieDesMagies":"33",
// "histoireMagique":"33",
// "magieAir":"33",
// "magieEau":"33",
// "magieTerre":"33",
// "magieFeu":"33",
// "magieElec":"33",
// "crea":"33",
// "psyInt":"33",
// "psyPerso":"33",
// "instinct":"33",
// "auraLectrice":"55",
// "chaleur":"44",
// "vapeur":"44",
// "magieVie":"44",
// "temps":"44",
// "mort":"44",
// "magnetisme":"44",
// "oxygene":"44",
// "foudre":"44",
// "flying":"44",
// "molecule":"44",
// "metaux":"44",
// "psyExt":"44",
// "psyInterperso":"44",
// "auraManipulatrice":"44",
// "genbu":"33",
// "oiseauTonnerre":"33",
// "ginnungagap":"33",
// "phoinix":"33",
// "klabautermann":"33",
// "thiyatHametim":"33",
// "mortemRejiciunt":"33",
// "yomHaDim":"33",
// "vitaBrevis":"33",
// "lostAge":"33",
// "sunganIdong":"33",
// "auraCombinatoire":"33",
// "lumiere":"33",
// "ombres":"33",
// "sang":"33",
// "fluides":"33",
// "energie":"33",
// "sons":"33",
// "magieAstrale":"33",
// "magieSpectrale":"33",
// "cosmos":"33",
// "savoir":"33",
// "tenebres":"33",
// "oubli":"33",
// "clairObscur":"33",
// "plantes":"33",
// "adn":"33",
// "fer":"33",
// "plasma":"33",
// "ondes":"33",
// "magieDraconique":"33"
// },
// {"_id":"639dc1fa2d088983c679611f",
// "name":"Perso test",
// "age":"358",
// "oeilD":"bleu",
// "oeilG":"vert",
// "taille":"190",
// "poids":"85",
// "sexe":"N.D.",
// "planete":"manta",
// "agence":"Estrella",
// "cheveux":"blonds",
// "race":"vemp'yr",
// "metier":"guerrier",
// "niveau":1,
// "signesDistinctifs":"bernbmonerm vkjmeboizrg veribvre gimub zrkg friumgb rkjgmbrgbrmigb kjgmbrrg eribg erkjmg g",
// "traitsDeCaractere":"ezogberomg jfezrngrle gjuierbgejkbtkr:ebgergjkgbgterjk brk biorhtn rkuhgerkgheroiv reiug h erjghejguie gnoidghnlk bhrlhdfoigfoigeroigheri gherio eoih greoi gheroi greig hrimdg",
// "manaAir":"100",
// "manaEau":"100",
// "manaTerre":"100",
// "manaFeu":"100",
// "stamina":"100",
// "manaVie":"400",
// "force":"50",
// "dexterite":"50",
// "resistance":"50",
// "resilience":"50",
// "intelligence":"50",
// "charisme":"50",
// "chance":"nr",
// "bien":"0",
// "mal":"25",
// "xalytienArchaique":"30",
// "xalytienAntique":"30",
// "xalytienDemonique":"30",
// "xentoArchaique":"30",
// "xentoAntique":"30",
// "xentoDemonique":"30",
// "zenolmArchaique":"30",
// "zenolmAntique":"30",
// "zenolmDemonique":"30",
// "justiccelArchaique":"30",
// "justiccelAntique":"30",
// "justiccelDemonique":"30",
// "zombique":"40",
// "faerik":"40",
// "elfik":"40",
// "nanien":"30",
// "gnomique":"50",
// "tenebriale":"30",
// "noyale":"20",
// "elementale":"30",
// "celeste":"45",
// "mainsNues":"43",
// "jets":"33",
// "contondantes":"23",
// "courtes":"33",
// "longues":"55",
// "esquive":"56",
// "parade":"44",
// "chant":"43",
// "chasse":"33",
// "course":"33",
// "crochetage":"44",
// "discretion":"33",
// "eloquence":"33",
// "equitation":"33",
// "escalade":"33",
// "herboristerie":"33",
// "hypnose":"33",
// "marchandage":"33",
// "medecine":"33",
// "nage":"33",
// "observation":"33",
// "pieges":"33",
// "pistage":"33",
// "professorat":"33",
// "saut":"33",
// "soin":"33",
// "survie":"33",
// "telekinesie":"33",
// "vigilence":"33",
// "magicoTech":"33",
// "cartographie":"33",
// "potions":"33",
// "theorieDesMagies":"33",
// "histoireMagique":"33",
// "magieAir":"33",
// "magieEau":"33",
// "magieTerre":"33",
// "magieFeu":"33",
// "magieElec":"33",
// "crea":"33",
// "psyInt":"33",
// "psyPerso":"33",
// "instinct":"33",
// "auraLectrice":"55",
// "chaleur":"44",
// "vapeur":"44",
// "magieVie":"44",
// "temps":"44",
// "mort":"44",
// "magnetisme":"44",
// "oxygene":"44",
// "foudre":"44",
// "flying":"44",
// "molecule":"44",
// "metaux":"44",
// "psyExt":"44",
// "psyInterperso":"44",
// "auraManipulatrice":"44",
// "genbu":"33",
// "oiseauTonnerre":"33",
// "ginnungagap":"33",
// "phoinix":"33",
// "klabautermann":"33",
// "thiyatHametim":"33",
// "mortemRejiciunt":"33",
// "yomHaDim":"33",
// "vitaBrevis":"33",
// "lostAge":"33",
// "sunganIdong":"33",
// "auraCombinatoire":"33",
// "lumiere":"33",
// "ombres":"33",
// "sang":"33",
// "fluides":"33",
// "energie":"33",
// "sons":"33",
// "magieAstrale":"33",
// "magieSpectrale":"33",
// "cosmos":"33",
// "savoir":"33",
// "tenebres":"33",
// "oubli":"33",
// "clairObscur":"33",
// "plantes":"33",
// "adn":"33",
// "fer":"33",
// "plasma":"33",
// "ondes":"33",
// "magieDraconique":"33"
// }
]